name: dreambooth
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - numpy
  - cudatoolkit=11.6
  - pytorch-lightning
  - pip:
    - diffusers[training]
    - accelerate
    - transformers
    - pyyaml
    - omegaconf